Feature/calculator
SmartTechnologyLab/opodatkuvayco pull request #26
Opened 2024-02-22 13:48 UTC by ZadorozhnyiYevhenii

2024-02-22 14:00 UTC, P0TER commented on src/components/TaxCalculator/TaxCalculator.stories.ts
> +export const Default = Template.bind({})
Nit: Это старый способ описания сторибука, но если работает то ок.

PS: nit — это не обязательный к выполнению комментарий

2024-02-22 14:12 UTC, P0TER commented on src/components/TaxCalculator/TaxCalculator.vue
> +          <button @click="handleDeleteFile(file)" class="calc__file-delete">X</button>
Пора создать свой компонент кнопки на основе Prime vue, но чтобы мы могли использовать только те, которые у нас сейчас требуются на проекте. а не все подряд, и по использовать тихонькую, будем добавлять те, что нужно.

2024-02-22 14:15 UTC, P0TER commented on src/components/TaxCalculator/TaxCalculator.vue
> +  gap: 1em;
em хорошо использовать в компонентах, когда он инкапсулирован родительским размером шрифта например, или ты понимаешь, что твой компонент будет вставлен в нужное место с нужным размером. В других же случаях лучше использовать rem

2024-02-22 14:17 UTC, P0TER commented on src/components/TaxCalculator/TaxCalculator.vue
Мне нравиться, верстка понятная, с БЕМ тоже все ок, круто

2024-02-22 14:24 UTC, ZadorozhnyiYevhenii commented on src/assets/main.scss
>  @import 'base.scss';
Забыл написать что use у меня чего-то не работает(

2024-02-22 14:26 UTC, ZadorozhnyiYevhenii commented on src/components/TaxCalculator/TaxCalculator.vue
Супер, сейчас пофикшу все))

2024-02-22 15:40 UTC, P0TER commented on src/assets/main.scss
>  @import 'base.scss';
Ок гляну сам

2024-02-22 19:39 UTC, ZadorozhnyiYevhenii commented
Добавил в vite config, что можно использовать глобально не с use, а с импортом

2024-02-27 19:37 UTC, P0TER requested changes

2024-02-27 19:37 UTC, P0TER commented on src/components/common/TaxCalculator/TaxCalculator.vue
> +  }
Не не давай в функциональном стиле)) 
И вынеси из функции `const chars = '1234567890+-'` иначе в таком случае константа создается на каждый вызов функции.

```suggestion
  const checkIsValid = (value) => value.split('').every(char => chars.includes(char))
```

2024-02-27 19:37 UTC, P0TER commented on src/components/common/TaxCalculator/TaxCalculator.vue
> +      @input="handleInput"
хочешь проверять каждый символ, сделай не через модель и @input, а через компьютед геттер сеттер тогда

2024-03-09 12:07 UTC, P0TER requested changes

2024-03-09 12:07 UTC, P0TER commented on src/components/common/UiButton/UiButton.vue
> +import type { Icons, Severities } from './constants'
enum это не тип, не путай, это константа, так будет ошибка при сборке потом будешь долго дебажить)

2024-03-09 12:07 UTC, P0TER commented on src/components/common/TaxCalculator/constants/index.ts
> +export const validChars = '0123456789+-/*'
точка или запятая не нужна?

2024-03-09 12:32 UTC, ZadorozhnyiYevhenii commented on src/components/common/UiButton/UiButton.vue
> +import type { Icons, Severities } from './constants'
Не заметил что так заимпортилось)

2024-03-09 12:53 UTC, merged