feat: added base routes
SmartTechnologyLab/opodatkuvayco pull request #29
Opened 2024-04-29 13:50 UTC by ZadorozhnyiYevhenii

2024-04-29 18:45 UTC, P0TER requested changes

2024-04-29 18:45 UTC, P0TER commented on src/components/common/UIInput/UIInput.stories.ts
> +import UIInput from './UIInput.vue'
```suggestion
import UiInput from './UiInput.vue'
```
Ui первое слово Input второе

2024-04-29 18:45 UTC, P0TER commented on src/router/routes.ts
> +  { path: '/policy', component: PolicyPage }
лучше сразу посмотреть в сторону динамического импорта, чтобы потом в перформанс не играться

2024-04-29 18:45 UTC, P0TER commented on src/components/common/UIInput/UIInput.vue
> +  <InputText type="text" />
Это из Прайма? или откуда?

2024-04-29 18:58 UTC, ZadorozhnyiYevhenii commented on src/components/NavBar/NavBar.vue
> +@import '../../assets/scss/mixins/_headings.scss';
Да, у нас же все еще проблемка осталась

2024-04-29 19:02 UTC, ZadorozhnyiYevhenii commented on src/components/common/UIInput/UIInput.vue
> +  <InputText type="text" />
Из прайма

2024-04-29 19:19 UTC, ZadorozhnyiYevhenii commented on src/components/common/UIInput/UIInput.vue
> +  <InputText type="text" />
А нет, чего-то не за импортилось, но работало)
Мб работает без импортов)

2024-04-29 19:46 UTC, ZadorozhnyiYevhenii commented
Ніби все пофіксив :)

2024-04-30 17:17 UTC, ZadorozhnyiYevhenii commented on src/components/NavBar/NavBar.vue
> +import UiImage from '../common/UiImage/UiImage.vue'
Окей, поправил

2024-04-30 17:34 UTC, ZadorozhnyiYevhenii commented
Интересно как у тебя прошел type-check когда ты поменял названия файла с UIInput на UiInput, когда я менял, то у меня падала джоба `PullRequest / type_check (pull_request) `

2024-04-30 17:34 UTC, P0TER commented
Нужно еще поменять название папки UIInput, файлы я уже поменял, нужно проверить импорты

2024-04-30 17:35 UTC, ZadorozhnyiYevhenii commented
Хотя вижу что со story тоже упала

2024-05-01 11:22 UTC, P0TER approved these changes

2024-05-01 11:26 UTC, merged