feat: wrapped ui-button with Component and fix some styles
SmartTechnologyLab/opodatkuvayco pull request #32
Opened 2024-05-01 21:35 UTC by ZadorozhnyiYevhenii

2024-05-06 13:12 UTC, P0TER requested changes

2024-05-06 13:12 UTC, P0TER commented on src/components/common/UiButton/UiButton.vue
> +  class?: string
что за класс?)

2024-05-06 13:12 UTC, P0TER commented on src/components/common/UiButton/UiButton.stories.ts
> +    <UiButton :key="severity" v-bind="{ ...args }" to='/google' />
./google - это как внутренний роут тут?

2024-05-06 13:15 UTC, ZadorozhnyiYevhenii commented on src/components/common/UiButton/UiButton.vue
> +  class?: string
Я так сделал из-за того что стили будут применятся и к Component и к самой кнопке, если брать class из attrs

2024-06-07 19:08 UTC, P0TER requested changes

2024-06-07 19:08 UTC, P0TER commented on src/components/common/UiButton/UiButton.vue
> +    <Button v-bind="{ ...props, ...attrs }" @click="$emit('clickBtn')">
Не не никаких clickBtn, все как нативная кнопка ивенты должны быть click нужно, тут походу и так навеститься клик вместе с атрибутами, возможно даже не надо об'являть тут емит

2024-06-07 19:10 UTC, ZadorozhnyiYevhenii commented on src/components/common/UiButton/UiButton.vue
> +    <Button v-bind="{ ...props, ...attrs }" @click="$emit('clickBtn')">
Да, херню сделал)

2024-06-09 12:08 UTC, ZadorozhnyiYevhenii commented on src/components/common/UiButton/UiButton.vue
> +  class?: string
Да, навешивался и на родителя, но я исправил

2024-06-12 10:37 UTC, P0TER approved these changes

2024-06-12 10:37 UTC, merged