refactor: splitted title
SmartTechnologyLab/opodatkuvayco pull request #33
Opened 2024-05-01 22:34 UTC by ZadorozhnyiYevhenii

Попробовал так зарефакторить. Тоже конечно костыль, но так код чище)

2024-05-06 13:16 UTC, P0TER requested changes

2024-05-06 13:16 UTC, P0TER commented on src/pages/HomePage.vue
> +      <h2 class="main-page__title" v-html="t('main.motto')"></h2>
так можно, но не желательно, + если файл переводов мы получаем с третего сервиса, то это может быть уязвимостью, в таких случаях лучше добавлять санитайзер, если действительно нужно что-то отренедерить.

В нашем же случае нам не обязательно так делать, есть другой подход.
Вот тут посмотри: https://vue-i18n.intlify.dev/guide/advanced/component.html

2024-05-06 13:16 UTC, P0TER commented on src/pages/HomePage.vue
> +<style lang="scss">
зачем убрали скопед?

2024-05-06 13:18 UTC, ZadorozhnyiYevhenii commented on src/pages/HomePage.vue
> +<style lang="scss">
С тем подходом что я сделал, со scoped стили не применялись

2024-05-06 13:18 UTC, ZadorozhnyiYevhenii commented on src/pages/HomePage.vue
> +      <h2 class="main-page__title" v-html="t('main.motto')"></h2>
Окей, гляну

2024-05-06 13:22 UTC, P0TER requested changes

2024-05-06 13:22 UTC, P0TER commented on src/pages/HomePage.vue
> +<style lang="scss">
Значит есть вероятность того, что подход так себе, нужно смотреть

2024-05-06 13:24 UTC, P0TER commented on src/pages/HomePage.vue
> +<style lang="scss">
нужно смотреть подход, и что не так, если что-то не получается, надо пересмотреть подход, возможно

2024-05-12 09:47 UTC, P0TER approved these changes

2024-05-12 09:47 UTC, P0TER commented on src/pages/HomePage.vue
> +      </i18n-t>
гуд

2024-05-12 09:48 UTC, merged