refactor: styles and extra types for ref`s
SmartTechnologyLab/opodatkuvayco pull request #37
Opened 2024-06-01 13:00 UTC by ZadorozhnyiYevhenii

2024-06-07 19:03 UTC, P0TER requested changes

2024-06-07 19:03 UTC, P0TER commented on src/components/common/TaxCalculator/TaxCalculator.vue
> +  console.log(files)
```suggestion
```

2024-06-07 19:03 UTC, P0TER commented on src/components/common/TaxCalculator/TaxCalculator.test.ts
> +    await wrapper.vm.$nextTick()
nextTick можно импортить из vue

2024-06-07 19:03 UTC, P0TER commented on src/components/common/TaxCalculator/TaxCalculator.test.ts
> +    fileInput.vm.$emit('change', { target: { files } })
trigger я так понял не сработал, а ты пробовал value изменить?

2024-06-07 19:03 UTC, P0TER commented on src/components/common/TaxCalculator/TaxCalculator.test.ts
> +    const equalBtn = wrapper.find('[data-testid="btn-equal"]')
дата тест атрибуты не особо хороший способ искать элементы, можно более нативно что-то придумать. так как это использует пользователь, можем потом обсудить

2024-06-07 19:03 UTC, P0TER commented on src/components/common/TaxCalculator/TaxCalculator.test.ts
> +import { shallowMount, type VueWrapper } from '@vue/test-utils'
гуд что используем shallowMount

2024-06-07 19:05 UTC, ZadorozhnyiYevhenii commented on src/components/common/TaxCalculator/TaxCalculator.test.ts
> +    fileInput.vm.$emit('change', { target: { files } })
Я уже посмотрел сегодня как Климов делал, поэтому попробую переделать)

2024-06-07 19:06 UTC, ZadorozhnyiYevhenii commented on src/components/common/TaxCalculator/TaxCalculator.test.ts
> +import { shallowMount, type VueWrapper } from '@vue/test-utils'
Стараюсь, но пока тяжело)

2024-06-12 10:34 UTC, P0TER approved these changes

2024-06-12 10:38 UTC, merged